/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FarmService } from "../farm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FarmCreateInput } from "./FarmCreateInput";
import { FarmWhereInput } from "./FarmWhereInput";
import { FarmWhereUniqueInput } from "./FarmWhereUniqueInput";
import { FarmFindManyArgs } from "./FarmFindManyArgs";
import { FarmUpdateInput } from "./FarmUpdateInput";
import { Farm } from "./Farm";
import { FarmActivityFindManyArgs } from "../../farmActivity/base/FarmActivityFindManyArgs";
import { FarmActivity } from "../../farmActivity/base/FarmActivity";
import { FarmActivityWhereUniqueInput } from "../../farmActivity/base/FarmActivityWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FarmControllerBase {
  constructor(
    protected readonly service: FarmService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Farm })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: FarmCreateInput): Promise<Farm> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        farmType: true,
        heightArea: true,
        id: true,
        lengthArea: true,
        sunlightAvailability: true,
        updatedAt: true,
        widthArea: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Farm] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(FarmFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Farm[]> {
    const args = plainToClass(FarmFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        farmType: true,
        heightArea: true,
        id: true,
        lengthArea: true,
        sunlightAvailability: true,
        updatedAt: true,
        widthArea: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Farm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: FarmWhereUniqueInput
  ): Promise<Farm | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        farmType: true,
        heightArea: true,
        id: true,
        lengthArea: true,
        sunlightAvailability: true,
        updatedAt: true,
        widthArea: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Farm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: FarmWhereUniqueInput,
    @common.Body() data: FarmUpdateInput
  ): Promise<Farm | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          farmType: true,
          heightArea: true,
          id: true,
          lengthArea: true,
          sunlightAvailability: true,
          updatedAt: true,
          widthArea: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Farm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: FarmWhereUniqueInput
  ): Promise<Farm | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          farmType: true,
          heightArea: true,
          id: true,
          lengthArea: true,
          sunlightAvailability: true,
          updatedAt: true,
          widthArea: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "FarmActivity",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/farmActivities")
  @ApiNestedQuery(FarmActivityFindManyArgs)
  async findManyFarmActivities(
    @common.Req() request: Request,
    @common.Param() params: FarmWhereUniqueInput
  ): Promise<FarmActivity[]> {
    const query = plainToClass(FarmActivityFindManyArgs, request.query);
    const results = await this.service.findFarmActivities(params.id, {
      ...query,
      select: {
        activityDate: true,
        createdAt: true,
        description: true,

        farm: {
          select: {
            id: true,
          },
        },

        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/farmActivities")
  async connectFarmActivities(
    @common.Param() params: FarmWhereUniqueInput,
    @common.Body() body: FarmActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      farmActivities: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/farmActivities")
  async updateFarmActivities(
    @common.Param() params: FarmWhereUniqueInput,
    @common.Body() body: FarmActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      farmActivities: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Farm",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/farmActivities")
  async disconnectFarmActivities(
    @common.Param() params: FarmWhereUniqueInput,
    @common.Body() body: FarmActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      farmActivities: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
